services:

  web:
    image: webserver
    build: ./server/
    volumes:
      - ./project:/usr/share/nginx/html
      - ./server/nginx/static:/www/data/static
    ports:
      - "80:80"
    restart: unless-stopped

  mysql:
    image: database
    build: ./database/
    volumes:
      - ./database/data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: unless-stopped

  app:
    image: app
    build: ./project/
    volumes:
      - ./project/NestFuture:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mysql
    ports:
      - "3000:3000"
